version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: springboot
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 12345678
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  mysql_data:
